package dependency;

public enum Relation {
	SUBJECT, NOM_MOD, NOM_DET, ROOT, PREP, OBJECT, POSS, APPOS, ELECT, VERB_COMPLEX, PREPOS_INF, SUBORD_CONJ, COORD_CONJ, ADJ, COMPL, INF_OBJ, NOM_QUANT, X, VERB_JUNCT, Y, COMMA
}
